### ISSUE TITLE
Missing amd/src/app-lazy.js

### ISSUE THREAD

**Issue by grabs** [lucaboesch/moodle-local_differentiator#15]
Hi,
is there a reason for the missing javascript source?
Where can I get this from?
Thanks!
Best regards
Andreas

**Comment by lucaboesch** [comment]
Dear Andreas
In my system amd/src/app-lazy.js is a link to amd/build/app-lazy.min.js.
Maybe the other contributors have a better answer to your question.
I'm sorry I can't halp you out right now.
Pinging @christianwolters @TobiGa and @hannes99.
Best,
Luca

**Comment by grabs** [comment]
Hi Luca,
thanks for your response! Yes the symbolic link is there. But only if you clone this plugin from git to a supported filesystem.
On windows or if you use the zip download from https://moodle.org/plugins/local_differentiator the symbolic link is converted to a small text file with the source path in it.
However, this is not the source code, but only the compiled version. This prevents me from compiling the script myself.
It would be really nice to have the source.
Regardless of that, the plugin itself looks really cool. Thanks all of you for that!
Best regards
Andreas

**Comment by grabs** [comment]
Hi,
is there some progress here?
I mean this project is declared as open source.
The source of the file "amd/build/app-lazy.min.js" must be somewhere or am I wrong?
So could you be so kind and publish the source? That would be really great!
Thank you!
Andreas

**Comment by lucaboesch** [comment]
Dear Andreas
I think the file "amd/build/app-lazy.min.js" is mainly built of "vue/main.js" when I do npm run dev.
Please refer to this source https://github.com/MartinGauk/moodle-mod_vuejsdemo/blob/master/README.md I took as base for this project.
Just asking: what happens if you take the "amd/build/app-lazy.min.js" file and you copy it over to "amd/src/app-lazy.js"?
The least thing I can say: there is no uncommited file here I don't publish on this repo!
So no hide and seek from my part…
Best,
Luca

**Comment by grabs** [comment]
Hi Luca,
thanks for your reply. But it doesn't explain, how to get the source which is needed to understand or rebuild the amd module :(.
Someone must have created the file somehow.
Thanks anyway!

**Comment by lucaboesch** [comment]
I think maybe for more insights you could try to get in touch with Martin Gauk?
But just for interest: what happens if you take the "amd/build/app-lazy.min.js" file and you copy it over to "amd/src/app-lazy.js" on a Windows system?

**Comment by grabs** [comment]
Thank you. But Martin Gauk is not one of the contributors of this plugin. So I doubt he has compiled this file.
Your suggestion to create the module may work technically, but it makes no sense at all. The result is the same file ;).
But I see this file shouldn't be public, so I have to live with it.
Best regards
Andreas

**Comment by christianwolters** [comment]
Hi @grabs 

thank you again for bringing attention to this issue.

I have no idea why there even is a app-lazy file in the amd/src - could this be due to any warning thrown by an IDE or linter or something like that.

As @lucaboesch mentioned: the js build is created from the vue js build.

So youhave to look at:

https://github.com/lucaboesch/moodle-local_differentiator/blob/master/vue/webpack.config.js

```js
  exports = {
        entry: './main.js',
        output: {
            path: path.resolve(__dirname, '../amd/build'),
            publicPath: '/dist/',
            filename: 'app-lazy.min.js',
            chunkFilename: "[id].app-lazy.min.js?v=[hash]",
            libraryTarget: 'amd',
        },

```

The code from the vue js project (residing in the vue directory) is compiled into app-lazy.min.js, starting from the entry point in main.js

So I agree with you that maybe that file should be there in src but your statement
`But I see this file shouldn't be public, so I have to live with it.`
is a bit misleading as the code is there - just not in the amd src.

Cheers
Christian

**Comment by grabs** [comment]
Hi Christian,
Thank you for the clarification! I really appreciate that. I didn't mean to offend you!
Could you mention that anywhere in the README? Maybe other people are just as confused as I was.
Thank you for this plugin!
Andreas

**Comment by lucaboesch** [comment]
I can totally do this, Andreas, with the next release.
Best,
Luca
